### ISSUE TITLE
Epic 1 - Kernel - User story 1: Access Kernel article from recent posts 

### ISSUE THREAD

**Issue by vvh24** [tomasGonz67/is373#19]
Description: Ensure the "Kernel" article is visible in the Recent Posts section. Clicking the article should redirect to the Kernel article page.

Acceptance Criteria:
The "Kernel" article is listed in Recent Posts.
Clicking redirects to the correct article.

Tasks:
Ensure the article is visible in Recent Posts.
Implement redirection to the article page.
Test redirection with Playwright.

**Comment by tomasGonz67** [comment]
done with html
