### ISSUE TITLE
1.4.1 User Story 1 - Accessing visual aids in the article to comprehend and distinguish the differences between VMs and Baremetal

### ISSUE THREAD

**Issue by xsylvers** [tomasGonz67/is373#25]
User Story: 
- As a user, student wants to see visual aids within the article to better understand the differences.

Acceptance Criteria:
- The VMs vs Baremetal article includes images, diagrams, or charts illustrating key concepts. Visual aids are appropriately labeled and referenced in the article text. Medium size, centered on the page.

**Comment by tomasGonz67** [comment]
closed
