### ISSUE TITLE
Epic 1 - Kernel - User story 2: Navigate between Kernel article by next and previous links  

### ISSUE THREAD

**Issue by vvh24** [tomasGonz67/is373#64]
Description: Add "Next" and "Previous" links to navigate between articles, allowing students to move smoothly between "Table of Contents," "Kernel," and "Containerization."

Acceptance Criteria:
Next/Previous links are visible at the bottom of the page.
Clicking redirects to the correct articles.

Tasks:
Implement Next/Previous links.
Test functionality for both links.

**Comment by tomasGonz67** [comment]
done with hexo
