### ISSUE TITLE
Epic 3 - Virtualization, VMs vs Baremetal, Containerization vs Virtualization - User story 1: Add href links to article headings for navigation

### ISSUE THREAD

**Issue by vvh24** [tomasGonz67/is373#67]
Description: Add href links to each heading in the article for easier navigation.

Acceptance Criteria:
Each heading includes a clickable link that redirects to the relevant section.

Tasks:
Add href links to headings.
Test link functionality with Playwright.

**Comment by tomasGonz67** [comment]
done in other repo
