### ISSUE TITLE
Epic 3 - Virtualization, VMs vs Baremetal, Containerization vs Virtualization - User story 2: Add share button/link to the bottom of the article

### ISSUE THREAD

**Issue by vvh24** [tomasGonz67/is373#68]
Description: Implement a share button at the bottom of the article that allows students to share the content via social media.

Acceptance Criteria:
A share button is visible and functional at the bottom of the article.

Tasks:
Add share button.
Test redirection to social media.

**Comment by tomasGonz67** [comment]
fixed witjh hexo
