### ISSUE TITLE
Epic 4 - Docker, WSL, Kubernetes vs Docker - User story 1: Display clear definition of "Containerization"

### ISSUE THREAD

**Issue by vvh24** [tomasGonz67/is373#69]
Description: Ensure that a clear definition of "Containerization" is visible at the top of the article.

Acceptance Criteria:
A section titled "Definition" is present at the top with a clear explanation.

Tasks:
Add the definition section.
Test the visibility and content of the definition.

**Comment by tomasGonz67** [comment]
fixed in md
